version: "3"
services:
  api:
    build: ./api
    ports:
      - 5000:5000
  db:
    build: ./postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
